---
- name: "{{ api_task_name }}"
  uri:
    body: "{{ api_body | default(omit) }}"
    body_format: "{{ api_body_format }}"
    client_cert: "{{ api_client_cert | default(omit) }}"
    client_key: "{{ api_client_key | default(omit) }}"
    creates: "{{ api_creates | default(omit) }}"
    dest: "{{ api_dest | default(omit) }}"
    follow_redirects: "{{ api_follow_redirects | default(omit) }}"
    force_basic_auth: "{{ api_force_basic_auth }}"
    headers: "{{ api_headers | default(omit) }}"
    method: "{{ api_method }}"
    others: "{{ api_others | default(omit) }}"
    password: "{{ api_pass }}"
    removes: "{{ api_removes | default(omit) }}"
    return_content: "{{ api_return_content | default(omit) }}"
    status_code: "{{ api_status_code }}"
    timeout: "{{ api_timeout | default(omit) }}"
    url: "{{ api_base_url }}/{{ api_url_path }}"
    user: "{{ api_user | default(omit) }}"
    validate_certs: "{{ api_validate_certs | default(omit) }}"
  register: "{{ api_register_var }}"
